Traceback (most recent call last):
  File "/Users/jvanscho/miniforge3/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/jvanscho/miniforge3/lib/python3.9/site-packages/nbclient/client.py", line 1093, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/jvanscho/miniforge3/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/jvanscho/miniforge3/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/Users/jvanscho/miniforge3/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/jvanscho/miniforge3/lib/python3.9/site-packages/nbclient/client.py", line 559, in async_execute
    await self.async_execute_cell(
  File "/Users/jvanscho/miniforge3/lib/python3.9/site-packages/nbclient/client.py", line 854, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Users/jvanscho/miniforge3/lib/python3.9/site-packages/nbclient/client.py", line 756, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Auto-setup when running on Google Colab
if 'google.colab' in str(get_ipython()):
    !pip install openml

# General imports
%matplotlib inline
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import openml as oml
import tensorflow.keras as tf
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mImportError[0m                               Traceback (most recent call last)
[0;32m/var/folders/0t/5d8ttqzd773fy0wq3h5db0xr0000gn/T/ipykernel_36951/2999747030.py[0m in [0;36m<module>[0;34m[0m
[1;32m      6[0m [0mget_ipython[0m[0;34m([0m[0;34m)[0m[0;34m.[0m[0mrun_line_magic[0m[0;34m([0m[0;34m'matplotlib'[0m[0;34m,[0m [0;34m'inline'[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      7[0m [0;32mimport[0m [0mnumpy[0m [0;32mas[0m [0mnp[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 8[0;31m [0;32mimport[0m [0mpandas[0m [0;32mas[0m [0mpd[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      9[0m [0;32mimport[0m [0mmatplotlib[0m[0;34m.[0m[0mpyplot[0m [0;32mas[0m [0mplt[0m[0;34m[0m[0;34m[0m[0m
[1;32m     10[0m [0;32mimport[0m [0mopenml[0m [0;32mas[0m [0moml[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/miniforge3/lib/python3.9/site-packages/pandas/__init__.py[0m in [0;36m<module>[0;34m[0m
[1;32m     20[0m [0;34m[0m[0m
[1;32m     21[0m [0;31m# numpy compat[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 22[0;31m [0;32mfrom[0m [0mpandas[0m[0;34m.[0m[0mcompat[0m [0;32mimport[0m [0mis_numpy_dev[0m [0;32mas[0m [0m_is_numpy_dev[0m  [0;31m# pyright: ignore # noqa:F401[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     23[0m [0;34m[0m[0m
[1;32m     24[0m [0;32mtry[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/miniforge3/lib/python3.9/site-packages/pandas/compat/__init__.py[0m in [0;36m<module>[0;34m[0m
[1;32m     16[0m [0;34m[0m[0m
[1;32m     17[0m [0;32mfrom[0m [0mpandas[0m[0;34m.[0m[0m_typing[0m [0;32mimport[0m [0mF[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 18[0;31m from pandas.compat.numpy import (
[0m[1;32m     19[0m     [0mis_numpy_dev[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[1;32m     20[0m     [0mnp_version_under1p21[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/miniforge3/lib/python3.9/site-packages/pandas/compat/numpy/__init__.py[0m in [0;36m<module>[0;34m[0m
[1;32m     21[0m [0;34m[0m[0m
[1;32m     22[0m [0;32mif[0m [0m_nlv[0m [0;34m<[0m [0mVersion[0m[0;34m([0m[0m_min_numpy_ver[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 23[0;31m     raise ImportError(
[0m[1;32m     24[0m         [0;34mf"this version of pandas is incompatible with numpy < {_min_numpy_ver}\n"[0m[0;34m[0m[0;34m[0m[0m
[1;32m     25[0m         [0;34mf"your numpy version is {_np_version}.\n"[0m[0;34m[0m[0;34m[0m[0m

[0;31mImportError[0m: this version of pandas is incompatible with numpy < 1.20.3
your numpy version is 1.19.5.
Please upgrade numpy to >= 1.20.3 to use this pandas version
ImportError: this version of pandas is incompatible with numpy < 1.20.3
your numpy version is 1.19.5.
Please upgrade numpy to >= 1.20.3 to use this pandas version

